const Map<String, String> enStrings = {
  '首页': 'Home',
  '设置': 'Settings',
  '加载中...': 'Loading...',
  '网络错误，请检查网络连接': 'Network error. Please check your connection.',
  '请求超时，请重试': 'Request timed out. Please try again.',
  '服务器错误': 'Server error. Please try later.',
  '暂无数据': 'No data available',
  '重试': 'Retry',
  '操作成功': 'Operation successful',
  '确认': 'Confirm',
  '取消': 'Cancel',
  '删除': 'Delete',
  '保存': 'Save',
  '编辑': 'Edit',
  '搜索': 'Search',
  '返回': 'Back',
  '错误': 'Error',
  '提示': 'Hint',
  '语言': 'Language',
  '主题': 'Theme',
  '深色模式': 'Dark Mode',
  '浅色模式': 'Light Mode',
  '中文简体': 'Chinese (Simplified)',
  '英语': 'English',
  '关于': 'About',
  '版本': 'Version',
};