name: f_demo
description: "A Flutter app framework with Bloc/Cubit, Dio, GoRouter, and .t extension translation."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Network
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Routing
  go_router: ^14.2.1

  # Dependency Injection
  get_it: ^7.7.0

  # Storage
  shared_preferences: ^2.2.3

  # UI
  cupertino_icons: ^1.0.8
  logger: ^2.3.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true